version: "2"
services:
  apple2js:
    container_name: "apple2js"
    build: .
    restart: always
    environment:
      - HOSTNAME="dev-box.localdomain"
    volumes:
      - ./:/home/node/app
    ports:
      - '8080:8080'

